# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nacao <nacao@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/06 15:40:12 by nacao             #+#    #+#              #
#    Updated: 2025/03/13 14:52:46 by nacao            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = myPhoneBook

SRC = contact.cpp phoneBook.cpp
OBJ = ($SRC:.cpp=.o)

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJ)